name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run make ci
      run: |
        make config
        make ci

        # Stop all containers
        docker stop `docker ps -qa`

        # Remove all containers
        docker rm `docker ps -qa`

        # Remove all images
        docker rmi -f `docker images -qa `

        # Remove all volumes
        docker volume rm $(docker volume ls -qf)

        # Remove all networks
        docker network rm `docker network ls -q`        
